package io.github.mzmknight.subtracker.sync

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import io.github.mzmknight.subtracker.core.Money
import io.github.mzmknight.subtracker.core.PlainDate
import io.github.mzmknight.subtracker.core.Projection

/**
 * The synced records — the complete set of things a device can create or change.
 *
 * Everything else in the app (charges, monthly totals, run rate) is derived from
 * these three by [Projection], which is why the whole sync payload is a few KB
 * regardless of how many years of history exist.
 */

@Serializable
data class SubscriptionRecord(
    override val id: String,
    @SerialName("updated_at") override val updatedAt: String,
    override val deleted: Boolean = false,
    val name: String = "",
    val vendor: String = "",
    val category: String = "other",
    val currency: String = "GBP",
    @SerialName("cycle_unit") override val cycleUnit: String = "month",
    @SerialName("cycle_count") override val cycleCount: Int = 1,
    @SerialName("anchor_date") override val anchorDate: String = "",
    override val status: String = "active",
    @SerialName("end_date") override val endDate: String? = null,
    @SerialName("trial_end") val trialEnd: String? = null,
    @SerialName("payment_method") val paymentMethod: String = "",
    val colour: String = "",
    val icon: String = "",
    val notes: String = "",
    /** "" follows the device's global setting, "off" never, "custom" uses the two below. */
    @SerialName("notify_mode") val notifyMode: String = "",
    @SerialName("notify_days_before") val notifyDaysBefore: Int = 3,
    /** Minutes since midnight, local time. */
    @SerialName("notify_minute") val notifyMinute: Int = 540,
) : Syncable, Projection.Schedule {
    val isLive: Boolean get() = !deleted && (status == "active" || status == "trial")
    val cycleLabel: String get() = Money.describeCycle(cycleUnit, cycleCount)
    val anchor: PlainDate? get() = PlainDate.parseOrNull(anchorDate)
    val trialEnds: PlainDate? get() = PlainDate.parseOrNull(trialEnd)
}

@Serializable
data class PricePeriodRecord(
    override val id: String,
    @SerialName("updated_at") override val updatedAt: String,
    override val deleted: Boolean = false,
    @SerialName("subscription") val subscriptionId: String = "",
    @SerialName("amount_minor") override val amountMinor: Long = 0,
    @SerialName("effective_from") override val effectiveFrom: String = "",
    val note: String = "",
) : Syncable, Projection.Price {
    val from: PlainDate? get() = PlainDate.parseOrNull(effectiveFrom)
}

/**
 * A deliberate change to one generated charge.
 *
 * Its id is derived from (subscriptionId, dueDate) by [OverrideId] rather than
 * being random — two devices skipping the same charge must produce the *same*
 * record so last-write-wins can settle it, instead of two rows both claiming it.
 */
@Serializable
data class ChargeOverrideRecord(
    override val id: String,
    @SerialName("updated_at") override val updatedAt: String,
    override val deleted: Boolean = false,
    @SerialName("subscription") val subscriptionId: String = "",
    @SerialName("due_date") val dueDate: String = "",
    val kind: String = KIND_SKIPPED,
    @SerialName("amount_minor") val amountMinor: Long? = null,
) : Syncable {
    companion object {
        const val KIND_SKIPPED = "skipped"
        const val KIND_REFUNDED = "refunded"
        const val KIND_AMOUNT = "amount"

        fun idFor(subscriptionId: String, dueDate: String): String =
            OverrideId.forCharge(subscriptionId, dueDate)
    }
}

/**
 * One user-level setting, keyed by its own name.
 *
 * These are the settings that describe the person rather than the machine — how
 * far ahead to remind, at what time, which currency to total in, what a euro is
 * worth. Settings that describe *this* device stay out of the synced set
 * entirely and never become one of these; see `AppSettings` for which is which.
 *
 * A record per key, rather than one record holding every setting. Both would
 * merge, but a single blob makes two unrelated edits collide: change the
 * reminder time on your phone and the home currency on your laptop, and
 * last-write-wins would keep one and silently drop the other. Keyed separately,
 * each is its own last-write-wins contest and both land.
 *
 * The id *is* the key, so two devices editing the same setting produce the same
 * record and the merge settles it — the same reasoning as [ChargeOverrideRecord]
 * deriving its id rather than minting a random one.
 */
@Serializable
data class SettingRecord(
    override val id: String,
    @SerialName("updated_at") override val updatedAt: String,
    override val deleted: Boolean = false,
    val value: String = "",
) : Syncable

/**
 * A charge as the UI sees it: generated by the engine, then adjusted by whatever
 * override applies. Never stored and never synced — recomputed on demand.
 */
data class ComputedCharge(
    val subscriptionId: String,
    val due: PlainDate,
    val amountMinor: Long,
    val currency: String,
    val override: ChargeOverrideRecord? = null,
) {
    val isSkipped: Boolean get() = override?.kind == ChargeOverrideRecord.KIND_SKIPPED
    val isRefunded: Boolean get() = override?.kind == ChargeOverrideRecord.KIND_REFUNDED
    val hasAmountOverride: Boolean get() = override?.kind == ChargeOverrideRecord.KIND_AMOUNT

    /** Mirrors effectiveAmountMinor() in the server engine. */
    val effectiveAmountMinor: Long
        get() = when {
            isSkipped -> 0
            isRefunded -> 0
            hasAmountOverride -> override?.amountMinor ?: amountMinor
            else -> amountMinor
        }

    /** Paid-vs-upcoming is derived, never stored, so history stays correctable. */
    fun isSettled(today: PlainDate): Boolean = due < today
}
