import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.compose.multiplatform)
    alias(libs.plugins.kotlin.compose)
}

kotlin {
    compilerOptions { jvmTarget.set(JvmTarget.JVM_17) }
}

// Kotlin and Java must agree, and compileJava would otherwise default to the
// build JDK (25) while Kotlin targets 17. Set here rather than via a toolchain
// so the build doesn't try to download a second JDK.
java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    implementation(project(":shared"))
    implementation(compose.desktop.currentOs)
    // The shared module declares these as `implementation`, so they are not
    // visible here — the app module supplies its own driver.
    implementation(libs.sqldelight.sqlite.driver)
    implementation(libs.sqldelight.runtime)
}

/**
 * Portable build: the same app image, plus a `portable.txt` marker that makes it
 * keep its database and settings in `data/` beside the executable instead of in
 * %LOCALAPPDATA% and the registry.
 *
 * The marker is added only here, never to the MSI, so one binary serves both.
 */
val portableMarker = tasks.register("portableMarker") {
    val output = layout.buildDirectory.file("tmp/portable/portable.txt")
    outputs.file(output)
    doLast {
        val file = output.get().asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            This file makes SubTracker portable.

            While it is here, SubTracker keeps everything in the `data` folder next to
            SubTracker.exe: your subscriptions, settings and device identity. Copy the
            whole folder to a USB stick and it comes with you, leaving nothing behind on
            the machine it ran on.

            Delete this file and SubTracker will instead use the normal Windows location,
            %LOCALAPPDATA%\SubTracker.
            """.trimIndent()
        )
    }
}

tasks.register<Zip>("packagePortable") {
    group = "compose desktop"
    description = "Builds a no-install portable folder as a zip."
    dependsOn("createDistributable", portableMarker)

    from(layout.buildDirectory.dir("compose/binaries/main/app/SubTracker")) { into("SubTracker") }
    from(portableMarker) { into("SubTracker") }

    archiveFileName.set("SubTracker-portable-1.0.0.zip")
    destinationDirectory.set(layout.buildDirectory.dir("compose/binaries/main/portable"))
}

compose.desktop {
    application {
        mainClass = "io.github.mzmknight.subtracker.desktop.MainKt"

        // Skiko (Compose's renderer) loads native libraries via System.load,
        // which JDK 25 flags as a restricted method and a future JDK will block
        // outright. Granting native access explicitly silences the warning now
        // and keeps the app working when that block lands.
        jvmArgs += "--enable-native-access=ALL-UNNAMED"

        nativeDistributions {
            // jpackage bundles a JVM runtime, so the installer is ~80 MB. That
            // is the price of sharing the Compose UI with Android, and for a
            // personal tool it buys a lot.
            targetFormats(TargetFormat.Msi)
            packageName = "SubTracker"
            packageVersion = "1.0.0"

            // jpackage builds a minimised runtime with jlink, which by default
            // leaves out java.sql — and SQLDelight's JDBC driver needs
            // DriverManager. Without this the packaged app starts, throws
            // NoClassDefFoundError during the first composition, and dies with
            // no window and no message. It only fails when packaged; running
            // through Gradle uses the full JDK and works fine.
            modules("java.sql", "java.naming", "jdk.unsupported")
            description = "Subscription tracker"
            vendor = "mzmknight"

            windows {
                menu = true
                shortcut = true
                // Must stay fixed across releases or Windows treats each build
                // as a different product and installs them side by side.
                upgradeUuid = "8F3A1C64-27B5-4E9D-9C1A-6D2B0E7A4F31"
                // Generated by tools/IconGen.java from the same drawing as the
                // Android icon. jpackage insists on .ico here — a PNG is
                // rejected outright — and it sets the exe, the Start menu entry,
                // the shortcut and the installer artwork all at once.
                iconFile.set(project.file("icons/subtracker.ico"))
            }
        }
    }
}
